### PR TITLE
Add hiscore file

### PR DESCRIPTION
**Pull request by laautarolopez**
Hi, I've added the vitetris-hiscores file and path in Makefile.

### CODE REVIEW

**Review by vicgeralds — COMMENTED** [review]
Why is this needed? Running `make install-hiscores` already creates an empty file.

**Review by vicgeralds — CHANGES_REQUESTED** [review]
The added empty file isn’t used in the Makefile. The high score file is meant for system-wide high scores, but you change it to be placed in the user home directory. High scores are always saved in .vitetris anyway.

**Comment by laautarolopez** [comment]
Captura de pantalla de 2020-10-28 17-04-39
Running make install-hiscores

**Comment by vicgeralds** [comment]
That doesn’t really answer the question. If /var/games doesn’t exist, HISCORE_FILENAME can be changed to something else. Or you can create it.

**Comment by laautarolopez** [comment]
> The added empty file isn’t used in the Makefile. The high score file is meant for system-wide high scores, but you change it to be placed in the user home directory. High scores are always saved in .vitetris anyway.

In which file is the empty file used?

**Comment by vicgeralds** [comment]
It’s not used. You added it without referencing it anywhere.

**Pull request closed without merging**
